[theme]
primaryColor = "#0891B2"
backgroundColor = "#F1F5F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[theme.sidebar]
primaryColor = "#0891B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
borderColor = "#CBD5E1"

[server]
headless = true
port = 8501
address = "127.0.0.1"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
